### ISSUE TITLE
log data rotation for html reports and screenshots

### ISSUE THREAD

**Issue by toschneck** [ConSol/sakuli#153]
* add a property `sakuli.log.maxAge` in days.
* deletes all files that are older than the defined days in the folder `sakuli.log.folder`.
* default: 14 days
* Called after test execussion

**Comment by toschneck** [comment]
property `sakuli.log.max.Age` have to be at least 1 day to preventing deleting currently used files

```
ERROR [2016-02-16 15:41:19.724] - error during the BASE64 encoding of the screenshot 'C:\Program Files\sakuli\test_suites\DEPARTMENTSHARE\_logs\_screenshots\2016_02_16_15_41_12_140_Can_t_find_id_NEW_path_C_P.jpg'
org.sakuli.exceptions.SakuliForwarderException: error during the BASE64 encoding of the screenshot 'C:\Program Files\sakuli\test_suites\DEPARTMENTSHARE\_logs\_screenshots\2016_02_16_15_41_12_140_Can_t_find_id_NEW_path_C_P.jpg'
	at org.sakuli.services.forwarder.gearman.model.builder.ScreenshotDivConverter.extractScreenshotAsBase64(ScreenshotDivConverter.java:89) [sakuli.jar:na]
	at org.sakuli.services.forwarder.gearman.model.builder.ScreenshotDivConverter.convert(ScreenshotDivConverter.java:61) [sakuli.jar:na]
	at org.sakuli.services.forwarder.gearman.model.builder.OutputBuilder.generateTestCaseScreenshotsHTML(OutputBuilder.java:190) [sakuli.jar:na]
	at org.sakuli.services.forwarder.gearman.model.builder.OutputBuilder.getTextPlaceholder(OutputBuilder.java:170) [sakuli.jar:na]
	at org.sakuli.services.forwarder.gearman.model.builder.OutputBuilder.formatTestCaseTableStateMessage(OutputBuilder.java:133) [sakuli.jar:na]
	at org.sakuli.services.forwarder.gearman.model.builder.OutputBuilder.getStatusSummary(OutputBuilder.java:123) [sakuli.jar:na]
	at org.sakuli.services.forwarder.gearman.model.builder.OutputBuilder.build(OutputBuilder.java:101) [sakuli.jar:na]
	at org.sakuli.services.forwarder.gearman.model.builder.NagiosCheckResultBuilder.extractData(NagiosCheckResultBuilder.java:95) [sakuli.jar:na]
	at org.sakuli.services.forwarder.gearman.model.builder.NagiosCheckResultBuilder.build(NagiosCheckResultBuilder.java:64) [sakuli.jar:na]
	at org.sakuli.services.forwarder.gearman.GearmanResultServiceImpl.saveAllResults(GearmanResultServiceImpl.java:64) [sakuli.jar:na]
	at org.sakuli.services.common.AbstractResultService.triggerAction(AbstractResultService.java:44) [sakuli.jar:na]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_66]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_66]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_66]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_66]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_66]
	at org.sakuli.services.TeardownServiceHelper.invokeTeardownServices(TeardownServiceHelper.java:33) ~[sakuli.jar:na]
	at org.sakuli.starter.SakuliStarter.runTestSuite(SakuliStarter.java:231) ~[sakuli.jar:na]
	at org.sakuli.starter.SakuliStarter.main(SakuliStarter.java:123) ~[sakuli.jar:na]
	Suppressed: java.nio.file.AccessDeniedException: C:\Program Files\sakuli\test_suites\DEPARTMENTSHARE\_logs\_screenshots\2016_02_16_15_41_12_140_Can_t_find_id_NEW_path_C_P.jpg
		at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83) ~[na:1.8.0_66]
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97) ~[na:1.8.0_66]
		at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102) ~[na:1.8.0_66]
		at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230) ~[na:1.8.0_66]
		at java.nio.file.Files.newByteChannel(Files.java:361) ~[na:1.8.0_66]
		at java.nio.file.Files.newByteChannel(Files.java:407) ~[na:1.8.0_66]
		at java.nio.file.Files.readAllBytes(Files.java:3152) ~[na:1.8.0_66]
		at org.sakuli.services.forwarder.gearman.model.builder.ScreenshotDivConverter.extractScreenshotAsBase64(ScreenshotDivConverter.java:81) [sakuli.jar:na]
		... 21 common frames omitted
ERROR [2016-02-16 15:41:19.811] - java.lang.RuntimeException: {{SAKULI_EX}}error during the BASE64 encoding of the screenshot 'C:\Program Files\sakuli\test_suites\DEPARTMENTSHARE\_logs\_screenshots\2016_02_16_15_41_12_140_Can_t_find_id_NEW_path_C_P.jpg'
ERROR [2016-02-16 15:41:19.820] - 	at org.sakuli.exceptions.SakuliExceptionHandler.stopExecutionAndAddExceptionToSahiReport(SakuliExceptionHandler.java:272)
ERROR [2016-02-16 15:41:19.822] - 	at org.sakuli.exceptions.SakuliExceptionHandler.processException(SakuliExceptionHandler.java:195)
ERROR [2016-02-16 15:41:19.824] - 	at org.sakuli.exceptions.SakuliExceptionHandler.handleException(SakuliExceptionHandler.java:170)
ERROR [2016-02-16 15:41:19.826] - 	at org.sakuli.services.forwarder.gearman.model.builder.ScreenshotDivConverter.extractScreenshotAsBase64(ScreenshotDivConverter.java:88)
ERROR [2016-02-16 15:41:19.829] - 	at org.sakuli.services.forwarder.gearman.model.builder.ScreenshotDivConverter.convert(ScreenshotDivConverter.java:61)
ERROR [2016-02-16 15:41:19.831] - 	at org.sakuli.services.forwarder.gearman.model.builder.OutputBuilder.generateTestCaseScreenshotsHTML(OutputBuilder.java:190)
ERROR [2016-02-16 15:41:19.834] - 	at org.sakuli.services.forwarder.gearman.model.builder.OutputBuilder.getTextPlaceholder(OutputBuilder.java:170)
ERROR [2016-02-16 15:41:19.837] - 	at org.sakuli.services.forwarder.gearman.model.builder.OutputBuilder.formatTestCaseTableStateMessage(OutputBuilder.java:133)
ERROR [2016-02-16 15:41:19.840] - 	at org.sakuli.services.forwarder.gearman.model.builder.OutputBuilder.getStatusSummary(OutputBuilder.java:123)
ERROR [2016-02-16 15:41:19.842] - 	at org.sakuli.services.forwarder.gearman.model.builder.OutputBuilder.build(OutputBuilder.java:101)
ERROR [2016-02-16 15:41:19.844] - 	at org.sakuli.services.forwarder.gearman.model.builder.NagiosCheckResultBuilder.extractData(NagiosCheckResultBuilder.java:95)
ERROR [2016-02-16 15:41:19.847] - 	at org.sakuli.services.forwarder.gearman.model.builder.NagiosCheckResultBuilder.build(NagiosCheckResultBuilder.java:64)
ERROR [2016-02-16 15:41:19.852] - 	at org.sakuli.services.forwarder.gearman.GearmanResultServiceImpl.saveAllResults(GearmanResultServiceImpl.java:64)
ERROR [2016-02-16 15:41:19.855] - 	at org.sakuli.services.common.AbstractResultService.triggerAction(AbstractResultService.java:44)
ERROR [2016-02-16 15:41:19.856] - 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
ERROR [2016-02-16 15:41:19.858] - 	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
ERROR [2016-02-16 15:41:19.860] - 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
ERROR [2016-02-16 15:41:19.862] - 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
ERROR [2016-02-16 15:41:19.864] - 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
ERROR [2016-02-16 15:41:19.866] - 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
ERROR [2016-02-16 15:41:19.869] - 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
ERROR [2016-02-16 15:41:19.871] - 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
ERROR [2016-02-16 15:41:19.877] - 	at org.sakuli.services.TeardownServiceHelper.invokeTeardownServices(TeardownServiceHelper.java:33)
ERROR [2016-02-16 15:41:19.880] - 	at org.sakuli.starter.SakuliStarter.runTestSuite(SakuliStarter.java:231)
ERROR [2016-02-16 15:41:19.882] - 	at org.sakuli.starter.SakuliStarter.main(SakuliStarter.java:123)
```
