### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by sni** [ConSol/sakuli#171]
With the 1.0.0 i get a new exception as warning:

```
INFO  [2016-03-04 16:07:20.781] - _wait(10000, _assertExists(_span("Direct Link")));
INFO  [2016-03-04 16:07:21.018] - _mouseOver(_span("Direct Link"), null);
INFO  [2016-03-04 16:07:21.254] - _sahi.setServerVar('___lastValue___1457107641080', _isVisible(_span("Direct Link"), true));
INFO  [2016-03-04 16:07:21.352] - _wait(10000, _isVisible(_span("Direct Link"), true));
INFO  [2016-03-04 16:07:21.493] - _assert(_isVisible(_span("Direct Link"), true));
INFO  [2016-03-04 16:07:21.730] - _sahi.setServerVar('___lastValue___1457107641582', _isVisible(_span("Direct Link"), true));
INFO  [2016-03-04 16:07:21.869] - _highlight(_span("Direct Link"), "red");
INFO  [2016-03-04 16:07:22.016] - _click(_span("Direct Link"), null);
WARN  [2016-03-04 16:07:22.748] - commandClass = >net.sf.sahi.command.Player< commandMethod = >getCurrentStep<
WARN  [2016-03-04 16:07:22.749] - java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.sf.sahi.command.CommandExecuter.execute(CommandExecuter.java:55)
        at net.sf.sahi.LocalRequestProcessor.handleDyn(LocalRequestProcessor.java:67)
        at net.sf.sahi.LocalRequestProcessor.getLocalResponse(LocalRequestProcessor.java:40)
        at net.sf.sahi.ProxyProcessor.processLocally(ProxyProcessor.java:209)
        at net.sf.sahi.ProxyProcessor.run(ProxyProcessor.java:86)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -45
        at java.lang.String.substring(String.java:1967)
        at net.sf.sahi.rhino.ScriptRunner.getFromStep(ScriptRunner.java:253)
        at net.sf.sahi.rhino.ScriptRunner.getPopupNameFromStep(ScriptRunner.java:238)
        at net.sf.sahi.rhino.ScriptRunner.getStepJSON(ScriptRunner.java:299)
        at net.sf.sahi.command.Player.getCurrentStep(Player.java:135)
        ... 9 more

WARN  [2016-03-04 16:07:23.058] - commandClass = >net.sf.sahi.command.Player< commandMethod = >getCurrentStep<
WARN  [2016-03-04 16:07:23.058] - java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.sf.sahi.command.CommandExecuter.execute(CommandExecuter.java:55)
        at net.sf.sahi.LocalRequestProcessor.handleDyn(LocalRequestProcessor.java:67)
        at net.sf.sahi.LocalRequestProcessor.getLocalResponse(LocalRequestProcessor.java:40)
        at net.sf.sahi.ProxyProcessor.processLocally(ProxyProcessor.java:209)
        at net.sf.sahi.ProxyProcessor.run(ProxyProcessor.java:86)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -45
        at java.lang.String.substring(String.java:1967)
        at net.sf.sahi.rhino.ScriptRunner.getFromStep(ScriptRunner.java:253)
        at net.sf.sahi.rhino.ScriptRunner.getPopupNameFromStep(ScriptRunner.java:238)
        at net.sf.sahi.rhino.ScriptRunner.getStepJSON(ScriptRunner.java:299)
        at net.sf.sahi.command.Player.getCurrentStep(Player.java:135)
        ... 9 more

```

**Comment by toschneck** [comment]
not valid any more
