### ISSUE TITLE
sakuli hangsup when `xdotool` is not installed

### ISSUE THREAD

**Issue by toschneck** [ConSol/sakuli#207]
If under Linux systems the `xdotool`is not installed, Sakuli hangs up with the following stacktrace:

```
INFO  [2016-09-23 18:02:25.481] - SHUTDOWN SAHI-Proxy SUCCESSFULLY
INFO  [2016-09-23 18:02:25.481] - ========== TEAR-DOWN SAKULI TEST SUITE 'example_xfce' ==========
ERROR [2016-09-23 18:02:25.513] - Exception in thread "main" java.lang.ExceptionInInitializerError
ERROR [2016-09-23 18:02:25.513] -   at org.sakuli.utils.CleanUpHelper.cleanClipboard(CleanUpHelper.java:47)
ERROR [2016-09-23 18:02:25.513] -   at org.sakuli.services.common.CommonResultServiceImpl.cleanUp(CommonResultServiceImpl.java:92)
ERROR [2016-09-23 18:02:25.513] -   at org.sakuli.services.common.CommonResultServiceImpl.saveAllResults(CommonResultServiceImpl.java:55)
ERROR [2016-09-23 18:02:25.513] -   at org.sakuli.services.common.AbstractResultService.triggerAction(AbstractResultService.java:44)
ERROR [2016-09-23 18:02:25.513] -   at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
ERROR [2016-09-23 18:02:25.513] -   at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
ERROR [2016-09-23 18:02:25.513] -   at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
ERROR [2016-09-23 18:02:25.514] -   at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
ERROR [2016-09-23 18:02:25.514] -   at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
ERROR [2016-09-23 18:02:25.514] -   at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
ERROR [2016-09-23 18:02:25.514] -   at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
ERROR [2016-09-23 18:02:25.514] -   at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
ERROR [2016-09-23 18:02:25.514] -   at org.sakuli.services.TeardownServiceHelper.invokeTeardownServices(TeardownServiceHelper.java:33)
ERROR [2016-09-23 18:02:25.514] -   at org.sakuli.starter.SakuliStarter.runTestSuite(SakuliStarter.java:226)
ERROR [2016-09-23 18:02:25.514] -   at org.sakuli.starter.SakuliStarter.main(SakuliStarter.java:121)
ERROR [2016-09-23 18:02:25.514] - Caused by: org.sikuli.natives.NativeCommandException: [error] [error] checking: command 'xdotool' is not executable, please check if it is installed and available!
ERROR [2016-09-23 18:02:25.514] -   at org.sikuli.natives.LinuxUtil.checkLibAvailability(LinuxUtil.java:52)
ERROR [2016-09-23 18:02:25.515] -   at org.sikuli.script.App.<clinit>(App.java:50)
ERROR [2016-09-23 18:02:25.515] -   ... 15 more
```

**Comment by toschneck** [comment]
Problem is the Throwalbe `ExceptionInInitializerError` which won't be catched somewhere, so catch this and ensure that the results will be saved.
