### ISSUE TITLE
Syntaxerror message is missleading

### ISSUE THREAD

**Issue by Griesbacher** [ConSol/sakuli#209]
When a syntax error was made in the Sakuliscript the error message does not give a hint what went wrong.
Here an example:
```javascript
var region = new Region();
region..mouseWheelDown(1);
```
The error:
```
ERROR [2016-10-06 17:31:30.404] - org.sakuli.exceptions.SakuliException: TypeError: [object Object] is not an xml object.
org.sakuli.exceptions.SakuliExceptionWithScreenshot: org.sakuli.exceptions.SakuliException: TypeError: [object Object] is not an xml object.
        at org.sakuli.exceptions.SakuliExceptionHandler.transformException(SakuliExceptionHandler.java:294) [sakuli.jar:na]
        at org.sakuli.exceptions.SakuliExceptionHandler.processException(SakuliExceptionHandler.java:182) [sakuli.jar:na]
        at org.sakuli.exceptions.SakuliExceptionHandler.handleException(SakuliExceptionHandler.java:170) [sakuli.jar:na]
        at org.sakuli.exceptions.SakuliExceptionHandler.handleException(SakuliExceptionHandler.java:305) [sakuli.jar:na]
        at org.sakuli.exceptions.SakuliExceptionHandler.handleException(SakuliExceptionHandler.java:309) [sakuli.jar:na]
        at org.sakuli.actions.TestCaseAction.handleException(TestCaseAction.java:266) [sakuli.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_101]
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161) [js-1.7R2.jar:na]
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247) [js-1.7R2.jar:na]
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:3330) [js-1.7R2.jar:na]
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:2487) [js-1.7R2.jar:na]
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164) [js-1.7R2.jar:na]
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398) [js-1.7R2.jar:na]
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065) [js-1.7R2.jar:na]
        at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:175) [js-1.7R2.jar:na]
        at org.mozilla.javascript.Context.evaluateString(Context.java:1104) [js-1.7R2.jar:na]
        at net.sf.sahi.rhino.RhinoScriptRunner.run(RhinoScriptRunner.java:114) [sakuli.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_101]
Caused by: org.sakuli.exceptions.SakuliException: TypeError: [object Object] is not an xml object.
```
Some kind of JavaScriptparser at the beginning of the test could solve such problems.

**Comment by toschneck** [comment]
add a syntax checker check before the suite starts the browser
