### ISSUE TITLE
sahi test not run with webpack dev server

### ISSUE THREAD

**Issue by toschneck** [ConSol/sakuli#295]
document issue and solution here.
add also hint for https://github.com/toschneck/openshift-example-bakery-ci-pipeline/issues/1

**Comment by toschneck** [comment]
**Problem**
Due to the fact that  is https://github.com/webpack/webpack-dev-server is pretty common, wie tested the following command:

    webpack-dev-server --inline --progress

And then run the sakuli test as normal and get the following error:
```bash
ERROR [2017-12-01 13:00:07.415] - _sahi.setServerVar('lastURL', window.document.location.href); Window/Domain not found:  popupNameFromStep=; derivedName=; windowName=; windowTitle=; wasOpened=0; domain=guestbook ... @CALL: /headless/sakuli/sakuli-v1.1.0-SNAPSHOT/libs/js/sakuli.js&n=179
org.sakuli.exceptions.SakuliExceptionWithScreenshot: _sahi.setServerVar('lastURL', window.document.location.href); Window/Domain not found:  popupNameFromStep=; derivedName=; windowName=; windowTitle=; wasOpened=0; domain=guestbook ... @CALL: /headless/sakuli/sakuli-v1.1.0-SNAPSHOT/libs/js/sakuli.js&n=179
	at org.sakuli.exceptions.SakuliExceptionHandler.transformException(SakuliExceptionHandler.java:265) [sakuli.jar:na]
	at org.sakuli.exceptions.SakuliExceptionHandler.processException(SakuliExceptionHandler.java:152) [sakuli.jar:na]
	at org.sakuli.exceptions.SakuliExceptionHandler.handleException(SakuliExceptionHandler.java:140) [sakuli.jar:na]
	at org.sakuli.exceptions.SakuliExceptionHandler.handleException(SakuliExceptionHandler.java:298) [sakuli.jar:na]
	at org.sakuli.aop.RhinoAspect.doHandleRhinoException(RhinoAspect.java:206) [sakuli.jar:na]
	at net.sf.sahi.report.Report.addResult(Report.java:93) [sakuli.jar:na]
	at net.sf.sahi.rhino.RhinoScriptRunner.run(RhinoScriptRunner.java:120) [sakuli.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: org.sakuli.exceptions.SahiActionException: _sahi.setServerVar('lastURL', window.document.location.href); Window/Domain not found:  popupNameFromStep=; derivedName=; windowName=; windowTitle=; wasOpened=0; domain=guestbook ... @CALL: /headless/sakuli/sakuli-v1.1.0-SNAPSHOT/libs/js/sakuli.js&n=179
	... 5 common frames omitted
....
ERROR [2017-12-01 13:00:12.332] - ERROR:
CASE "tests": _sahi.setServerVar('lastURL', window.document.location.href); Window/Domain not found:  popupNameFromStep=; derivedName=; windowName=; windowTitle=; wasOpened=0; domain=guestbook ... @CALL: /headless/sakuli/sakuli-v1.1.0-SNAPSHOT/libs/js/sakuli.js&n=179
```

Because of the auto-reload function of the webpack server, Sahi will never get a point, where no ajax is open. Or only a few second, so that errors occurs with `Window/Domain not found:  popupNameFromStep=; derivedName=; windowName=; windowTitle=; wasOpened=0; `. This is also reproducible for a standalone Sahi OS installation.

**Solution:**
webpack-dev-server have to disable the auto-reload function with the option `--no-inline`, from [StackOverflow - How to disable webpack dev server auto reload?](https://stackoverflow.com/a/41943930/5243998). In a example `package.json`, it can look like:
```json
...
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "e2e-server": "webpack-dev-server --no-inline --progress --config build/webpack.dev.conf.js",
  },
```
