### ISSUE TITLE
TypeError while testCase.saveResult

### ISSUE THREAD

**Issue by kkensy** [ConSol/sakuli#332]
After a successfully testcase, the saveResult method throws occasionally an TypeError. Here the Logs:

```
...
INFO  [2018-07-16 21:10:37.184] - =========== SAVE Test Case 'XXX' ==================
INFO  [2018-07-16 21:10:37.185] - Forward of test case results enabled:  'false'
INFO  [2018-07-16 21:10:37.826] - _sahi.setServerVar('lastURL', window.document.location.href);
INFO  [2018-07-16 21:10:41.243] - _sahi.setServerVar('browser', navigator.userAgent);
INFO  [2018-07-16 21:10:41.374] - _sahi.setServerVar('browser', navigator.userAgent);
INFO  [2018-07-16 21:10:41.399] - create screen shot for error "TypeError: Cannot call method "replace" of null => ERROR ... @CALL: /headless/sakuli/sakuli-v1.2.0/libs/js/sakuli.js&n=179"
INFO  [2018-07-16 21:10:41.755] - screen shot saved to file "/xxx/_logs/_screenshots/2018_07_16_21_10_41_399_TypeError_Cannot_call_meth.png"
ERROR [2018-07-16 21:10:41.756] - TypeError: Cannot call method "replace" of null => ERROR ... @CALL: /headless/sakuli/sakuli-v1.2.0/libs/js/sakuli.js&n=179
org.sakuli.exceptions.SakuliExceptionWithScreenshot: TypeError: Cannot call method "replace" of null => ERROR ... @CALL: /headless/sakuli/sakuli-v1.2.0/libs/js/sakuli.js&n=179
        at org.sakuli.exceptions.SakuliExceptionHandler.transformException(SakuliExceptionHandler.java:280) [sakuli.jar:na]
        at org.sakuli.exceptions.SakuliExceptionHandler.processException(SakuliExceptionHandler.java:158) [sakuli.jar:na]
        at org.sakuli.exceptions.SakuliExceptionHandler.handleException(SakuliExceptionHandler.java:146) [sakuli.jar:na]
        at org.sakuli.exceptions.SakuliExceptionHandler.handleException(SakuliExceptionHandler.java:323) [sakuli.jar:na]
        at org.sakuli.aop.RhinoAspect.doHandleRhinoException(RhinoAspect.java:232) [sakuli.jar:na]
        at net.sf.sahi.report.Report.addResult(Report.java:93) [sakuli.jar:na]
        at net.sf.sahi.rhino.RhinoScriptRunner.run(RhinoScriptRunner.java:124) [sakuli.jar:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]
Caused by: org.sakuli.exceptions.SahiActionException: TypeError: Cannot call method "replace" of null => ERROR ... @CALL: /headless/sakuli/sakuli-v1.2.0/libs/js/sakuli.js&n=179
        ... 5 common frames omitted
INFO  [2018-07-16 21:10:41.757] - Total Memory in JVM (Xmx) is: 311.5 MB;<br/>Memory currently in use is: 114.5 MB;<br/>Memory increment during this test is: 28 MB
...
```

**Comment by s1hofmann** [comment]
Could you please proved a bit more info? Which browser are you running on which image?

**Comment by kkensy** [comment]
It is chromium-browser=66.0.3359.181-0ubuntu0.16.04.1 in a modified consol/sakuli-ubuntu-xfce:v1.2.0 Image.
