### ISSUE TITLE
OpenSUSE: error creating screenshot

### ISSUE THREAD

**Issue by simonmeggle** [ConSol/sakuli#82]
Test case "example_opensuse" causes a Java exception when Sakuli wants to store a screenshot: 
```
ERROR [2015-05-07 11:44:14.233] - Exception in thread "Thread-16" java.lang.UnsatisfiedLinkError: com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Ljava/lang/Class;Ljava/lang/Class;)V
ERROR [2015-05-07 11:44:14.254] -       at com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Native Method)
ERROR [2015-05-07 11:44:14.264] -       at com.sun.imageio.plugins.jpeg.JPEGImageWriter.<clinit>(JPEGImageWriter.java:186)
ERROR [2015-05-07 11:44:14.265] -       at com.sun.imageio.plugins.jpeg.JPEGImageWriterSpi.createWriterInstance(JPEGImageWriterSpi.java:96)
ERROR [2015-05-07 11:44:14.265] -       at javax.imageio.spi.ImageWriterSpi.createWriterInstance(ImageWriterSpi.java:351)
ERROR [2015-05-07 11:44:14.265] -       at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:843)
ERROR [2015-05-07 11:44:14.265] -       at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:827)
ERROR [2015-05-07 11:44:14.266] -       at javax.imageio.ImageIO.getWriter(ImageIO.java:1596)
ERROR [2015-05-07 11:44:14.269] -       at javax.imageio.ImageIO.write(ImageIO.java:1578)
ERROR [2015-05-07 11:44:14.270] -       at org.sakuli.actions.screenbased.ScreenshotActions.createPictureFromBufferedImage(ScreenshotActions.java:120)
ERROR [2015-05-07 11:44:14.320] -       at org.sakuli.actions.screenbased.ScreenshotActions.takeScreenshotAndHighlight(ScreenshotActions.java:72)
ERROR [2015-05-07 11:44:14.322] -       at org.sakuli.exceptions.SakuliExceptionHandler.transformException(SakuliExceptionHandler.java:274)
ERROR [2015-05-07 11:44:14.329] -       at org.sakuli.exceptions.SakuliExceptionHandler.processException(SakuliExceptionHandler.java:156)
ERROR [2015-05-07 11:44:14.331] -       at org.sakuli.exceptions.SakuliExceptionHandler.handleException(SakuliExceptionHandler.java:144)
ERROR [2015-05-07 11:44:14.334] -       at org.sakuli.exceptions.SakuliExceptionHandler.handleException(SakuliExceptionHandler.java:304)
ERROR [2015-05-07 11:44:14.335] -       at org.sakuli.actions.screenbased.RegionImpl.find(RegionImpl.java:89)
ERROR [2015-05-07 11:44:14.347] -       at org.sakuli.actions.screenbased.Region.find(Region.java:107)
ERROR [2015-05-07 11:44:14.350] -       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ERROR [2015-05-07 11:44:14.352] -       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ERROR [2015-05-07 11:44:14.356] -       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ERROR [2015-05-07 11:44:14.358] -       at java.lang.reflect.Method.invoke(Method.java:497)
ERROR [2015-05-07 11:44:14.371] -       at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
ERROR [2015-05-07 11:44:14.373] -       at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
ERROR [2015-05-07 11:44:14.378] -       at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:3330)
ERROR [2015-05-07 11:44:14.380] -       at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:2487)
ERROR [2015-05-07 11:44:14.381] -       at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
ERROR [2015-05-07 11:44:14.385] -       at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
ERROR [2015-05-07 11:44:14.386] -       at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
ERROR [2015-05-07 11:44:14.389] -       at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:175)
ERROR [2015-05-07 11:44:14.402] -       at org.mozilla.javascript.Context.evaluateString(Context.java:1104)
ERROR [2015-05-07 11:44:14.403] -       at net.sf.sahi.rhino.RhinoScriptRunner.run(RhinoScriptRunner.java:114)
ERROR [2015-05-07 11:44:14.411] -       at java.lang.Thread.run(Thread.java:745)
INFO  [2015-05-07 11:44:16.043] - test suite 'example_opensuse' stopped at 2015_05_07_11_44_16_43
INFO  [2015-05-07 11:44:16.044] - Sahi-Script-Runner executed with SUCCESS
INFO  [2015-05-07 11:44:16.044] - test suite finished
INFO  [2015-05-07 11:44:16.045] - SHUTDOWN SAHI-Proxy SUCCESSFULLY
INFO  [2015-05-07 11:44:16.194] - 
```

**Comment by simonmeggle** [comment]
Solution: change property `sakuli.screenshot.format`to `png`.

**Comment by simonmeggle** [comment]
Reason: OpenJDK obviously ships with a broken JPEG library: 
http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=1393

**Comment by simonmeggle** [comment]
Solved
